// DELETE http://localhost:5000//api/enrollments/{id}
// Content-Type: application/json

//{
//  "studentId": "S-001",
  //"courseCode": "CS-001"
// } 

GET http://localhost:5000/api/enrollments

# POST http://localhost:5000/api/enrollments
# Content-Type: application/json

# {
#   "studentId": "S-001",
#   "courseCode": "CS-001"
# }